### ISSUE TITLE
Supporting PowerPlay PvP in EDR

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#132]
It would be nice if EDR offered a mode tailored to Powerplay PvP.
Unclear if the game share enough information but some ideas would be:
 - Report enemies differently than unpledged ships
 - Allow power pledged players to issue query such as !enemies to find out where the players pledged to opposite powers are (e.g. Aisling pledged player runs !enemies, find out that Cmdr A pledged to Felicia is in system X, etc.)
 - possibly more.

**Comment by braxhunter** [comment]
Also it would be good to use Inara to find out a true pledge as there are groups that are pledged to a power then cmdrs are switching powers to get PP modules. So Inara would have data on the commander and who they are truly pledged too.  Most of the bigger groups require that you be pledged via inara in game not as much when farming PP modules.

**Comment by lekeno** [comment]
Thanks braxhunter for the feedback.

As of 0.7.6, EDR shows Power Allegiance from Inara.

The game doesn't output the in-game allegiance of other players, it only says Clean / Wanted / Enemy / WantedEnemy / Unknown (upon a regular scan).

**Comment by lekeno** [comment]
I've made lots of progress but still not quite done.
In particular, I have not started to work on the backend yet. I will need to upgrade the current code first (see issue #127)

The plan:
 - !enemies, ?enemies commands similar to !outlaws, ?outlaws
 - !where should also look into enemies of your power
 - Access to enemy information will be restricted to long standing pledges, e.g. at least x week(s).
  - x is TBD, suggestions welcomed. 
  - pledged time will be based on EDR info which means that it will start at 0 for everyone regardless of in-game info (can't trust the client)
  - I might start with a few days, then increase to a week, and perhaps a bit more than what it takes to get the power specific modules. 
 - sitreps will have an enemy section for powerplay pledges.
 - EDR will show a warning for enemies (in-game or inara info).

**Comment by lekeno** [comment]
TODOs:
 - [x] create the powerplay nodes on the server
 - [ ] setup access rules for powerplay nodes
 - [ ] update the scans backend function to report enemies in the right place
 - [ ] consider system to avoid reporting cmdrs pledged to the same power than oneself
 - [ ] (maybe a lot more)

**Comment by lekeno** [comment]
Access rules:
 - [ ] powerplay/: no access
 - [ ] powerplay/{power}/ no access
 - [ ] powerplay/{power}/{enemies}: read only for authenticated users who are also longstanding pledges to {power}
 - [ ] powerplay/{power}/pledges: can create one's node, power must match, can't be pledged elsewhere.

**Comment by lekeno** [comment]
Reacting to a pledge request:
 - initialize adjustedSince to since
 - if the player is already pledged, then remove that entry and set adjustedSince to max(now - a few days, since)

This should give a 1 chance of being grandfathered in.

**Comment by lekeno** [comment]
Getting close.

Public beta for 0.8.0 https://github.com/lekeno/edr/releases/tag/v0.8.0-beta.4

New features:
 - Added support for Powerplay PVP: 
  - Cmdr pledged to a power will report enemies to EDR upon scan for the benefit of other allied EDR users.
  - Enemy info in Intel, and Sitrep
  - New commands: `!enemies` to see the most recently sighted enemies, `?enemies [on|off|ly ###|cr ###]` for realtime alerts of enemies. These commands will only be available to long term pledges (30 days after the beta; 7 days at the moment) to avoid shenanigans with shifting between powers.
  - Inara info about allegiance is taken into account (should work, crossing fingers)
 - Added sticky comment about checking ED's focus after the overlay starts
 - Added support for Warrant, Enemy, WantedEnemy legal status.
 - Changed Karma's readable names from Wanted +++ to Outlaws +++ to avoid confusion between a player's tendencies and the in-game bounty status
 - Backend changes to accomodate Powerplay related features


Bug fixes:
 - Fixed issue with clock skew (some recent reports could be dropped if the computer's clock was off)
 - Fixed issue with "last 10 days's Legal Records" not always showing up (in fact rarely).
 - Fixed issue with Inara info not showing up on scan
 - Fixed issue with distance calculation, resulting in broken realtime alerts

**Comment by lekeno** [comment]
I think we are done here, hopefully I got the power names correctly ;)
