### ISSUE TITLE
Consider adding an SOS command

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#150]

**Comment by inorton** [comment]
A panic button keyboard shortcut might be nice, bash say, F12 and help is on the way?

**Comment by lekeno** [comment]
Yeah, smashing a key shortcut would be useful too as it might not always be possible to issue a command in local depending on the circumstances :)

Originally suggested by Cmdr Na'Qan. Paraphrasing: like a fuel rat alert but for combat/dangerous situations. Ability to send an SOS to update all EDR users of system. If an Outlaw responds, the cmdr who requested for help would know via EDR (e.g. alert) and not accept the offer.

Still needs some thinking (and avoiding ballooning up server costs) but it's an interesting idea.

**Comment by inorton** [comment]
It would be very cool, if when that happened, if someone else were nearby that they'd get the alert

**Comment by lekeno** [comment]
Hypothetical scenario:
 - Cmdr Ed is attempting to land at an engineer base in a half-finished ship when an outlaw suddenly starts to attack. Ed barely manages to jump away in a nearby system called EOL PROU XI (dummy)
 - EDR didn't capture anything interesting to alert other users and potential helpers (the journal doesn't contain enough info about attacks, only deaths and interdictions).
 - Cmdr Ed wants to warn other EDR users and ask for help to dislodge the base camper.
 - Cmdr Ed sends the following command in local chat (or any other channel actually): `!sos got attacked at Palin's base by a lonewolf FDL`
 - EDR users who are listening for SOS get a notification on their screen that reads: 
```
[EDR Alerts]
SOS from Ed: "got attacked at Palin's base by a lonewolf FDL" [### ly]
```

 - Cmdr Ted who is nearby and willing to help sends a friend request to Ed.
 - To be continued...
