### ISSUE TITLE
Alternative UI: EDMC panel which should work with VR via OVRDrop

### ISSUE THREAD

**Issue by Farinhir** [lekeno/edr#171]
I play Elite in VR and usually just use OVRDrop to inject EDMC into my display. I have been trying to find a way to just have the overlay displayed, but it seems that it also displays everything under the overlay also (so I end up with a ghost image of the game on the monitor). I wonder how hard it would be to allow us to set a black background or have the overlay able to be popped out from the game window. I know this might need to be directed at @inorton rather than you and will probably do so. I was just asking here first. 

Thank you for your work. These tools are all amazing. I just wish there were more VR support out there (at least for using injectors like I have above).

**Comment by lekeno** [comment]
Thanks for reaching out.
Yes, this sounds more a request for inorton.
However, I could also provide an alternative output in the form of a panel in EDMC.

I wish I was able to experience the game in VR and try out a few options for EDR ;)

**Comment by drsgfire** [comment]
I can give a big second on that. I literally just found out about all this a few days ago. Just got everything setup only to find it doesn't pop up in VR :(

I'd be more than happy to help test anything for you guys.

**Comment by inorton** [comment]
Hmm.  I'm not sure where to start.    Using OVRDrop sounds your best bet

**Comment by lekeno** [comment]
I can try an EDMC panel if you can already use OVRDrop to have it visible somewhere.

**Comment by lekeno** [comment]
OK, v 0.8.7 has a new UI in the EDMC app.

The status bar has an expandable UI element which reveals a window showing a log of messages from EDR. The colors, number of lines and characters per line can be configured (see config/igm_alt_config.v2.ini for instructions).

I'll release it soon.

**Comment by nullx8** [comment]
quick question, how do i get it to work in va using steam/oculusvr ? 
it shows perfectly fine on the screen, but I can;t get it to work in VR

**Comment by lekeno** [comment]
Hopefully this helps: https://www.youtube.com/watch?v=BPJFV4ycP3k

You need to change the overlay to be standalone in the EDR settings (accessible via ED Market Connector), and then add the standalone overlay via SteamVR's overlay feature (while already in VR).
