### ISSUE TITLE
Blip failed

### ISSUE THREAD

**Issue by kjrooney** [lekeno/edr#179]
I want to use your addon and i have installed it as instructed, however in the EDMC box it has the message blip failed. Can you please advise what this means and how i can fix it.

**Comment by lekeno** [comment]
Hi.

Did you [apply](https://lekeno.github.io/) for an account?

Note that you don't need for the basic features, just don't fill anything for the email and password in File => Settings => EDR tab.

**Comment by kjrooney** [comment]
Thanks, I have sent a message to you to apply for an account. There is nothing in the email and password in file settings EDR tab but still getting the same message.

**Comment by lekeno** [comment]
Apologies. I tried to see if you were online when I was but no luck.
I'll just reach out to your email address (no spam, I swear).

**Comment by lekeno** [comment]
Check your inbox.

2018年6月26日(火) 22:23 kjrooney <notifications@github.com>:
