### ISSUE TITLE
Latest 0.8.7 version is not working

### ISSUE THREAD

**Issue by rjotto** [lekeno/edr#189]
Greetings,

As in the title. It started with the plugin asked to restart EDMC to finishing the update. After restart, the plugin still asked for restart. So I removed the plugin and dowloaded manually. The link here is leading to a corrupted file: https://github.com/lekeno/edr/releases/tag/v0.8.7 so I dowloaded the source code, but that wont work too. So I went to here: https://github.com/lekeno/edr/tree/v0.8.7 and downloaded the zip from here. The archive was valid, but the issue is the same: EDMC cannot recognise the plugin. I hope the wall of info above helps :)

Regards, 
Otto

**Comment by lekeno** [comment]
Thanks for reaching out.

The archive was corrupted, I've re-uploaded a new version within a few hours of the first release.
Can you try again: https://github.com/lekeno/edr/releases/latest ?

If it still doesn't work, can you share the EDMarketConnector.log file from your temp folder?
See https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#reporting-a-problem for instructions. Feel free to reach out directly via discord: LeKeno#8484.


Thanks!

**Comment by rjotto** [comment]
Hi,

Glad if I can help.
It works now, thanks for your time and support!

Have a nice day and regards,

Otto

LeKeno <notifications@github.com> ezt írta (időpont: 2018. aug. 7., K,
10:03):

**Comment by lekeno** [comment]
Thanks for getting back on this.
o7!
