### ISSUE TITLE
Plugin not loading with EDMC 3.3.1.0

### ISSUE THREAD

**Issue by Rocangus** [lekeno/edr#216]
I tried installing EDR with EDMC 3.3.1.0 today but the plugin isn't loading for some reason. It's got the load.py file in the parent directory which is under plugins together with some other plugins that are loading (each plugin in its' own folder). Not sure if I have done something incorrectly here or if others are also experiencing this.

**Comment by lekeno** [comment]
Thanks for the bug report.
I wasn't able to reproduce this issue (loads fine for me with 3.3.1.0).

Could you share your EDMarketConnector.log file located in your temp directory?
 - See [more details here](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#reporting-a-problem)
 - Feel free to open it with notepad, to check if there is anything you would like to remove before sharing its content.

**Comment by lekeno** [comment]
That looks like an error due to an incorrect/obsolete or missing config file in the config folder, in particular the config.ini file.

I suggest re-downloading the [latest version](http://github.com/lekeno/edr/releases/latest)

**Comment by Rocangus** [comment]
Turns out I made the mistake of downloading the master branch from the github instead of the proper compressed folder. My apologies.
