### ISSUE TITLE
Equipment requirements

### ISSUE THREAD

**Issue by Rocangus** [lekeno/edr#217]
For instance, searching for Polonium tells you that you need an SRV and an Advanced Scanner. Shouldn't the Advanced Scanner be possible to remove since the FSS included in all ships gives you material information since chapter 4?

**Comment by lekeno** [comment]
Thanks for the feedback.
I think you might be right, the new chapter probably changes the requirements.

I originally added the Advanced Scanner as a requirement to find the planet (assuming that there was no navigation beacon in the system).
