### ISSUE TITLE
Incompatible with autopath EDMC plugin

### ISSUE THREAD

**Issue by Paspasote** [lekeno/edr#246]
EDMC runs well with one of them (either edr or autopath) but It does not run with both installed.

**Comment by lekeno** [comment]
Thanks for filing an issue. Could you check your temp folder for a file named EDMarketConnector.log ? Open it with notepad, and let me know if you can spot specific errors (redact your username in the path, etc).

I'll see if I can reproduce on my end too.

**Comment by Sognus** [comment]
Hello,

This issue was caused by [EDMC Autopath](https://github.com/Sognus/EDMC-Autopath). I pushed a fix into it's 1.1.0 version release. Please mark any issues using EDMC Autopath version 1.0.0 as wontfix.

Thanks, 
EDMC Autopath Author.
