### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#270]
End of Fife for Python 2.7 is coming fast, EDMC is working on a migration to Python 3 which will break plugins that don't. It's time to get going.

https://github.com/Athanasius/EDMarketConnector/tree/python3-2019

**Comment by lekeno** [comment]
Ideally, this should be done in a way that allows smooth migration, i.e. having a release that supports both python 2 and 3.

TODOs:
 - [ ] plugin_start3(plugin_dir) instead of plugin_start()
 - [ ] check that plugin_prefs, prefs_changed, journal_entry, dashboard_entry, and cmdr_data are declared with the correct number of arguments.
 - [ ] port the code to Python 3.7
 - [ ] keep the plugin working in both 2.7 and 3.7

**Comment by lekeno** [comment]
py-3.7 branch should work.

**Comment by feiercrack** [comment]
.still not working
