### ISSUE TITLE
Overlay can take over focus if the text is clicked on

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#279]
Example of when this can happen: when someone uses the mouse on the galaxy map and clicks on EDR's overlayed text, e.g. sitrep.

Options:
 - per mode layout to allow users to move EDR's text to neutral areas of the screen, or hiding specific categories
 - clear everything when entering a mode that's likely to trigger the issue
 - modify the overlay code so that it doesn't capture the mouse clicks

**Comment by DeadMor0z** [comment]
Overlay's code was modified by me resently. Also fixed flicker.

**Comment by lekeno** [comment]
Excellent. I've been running it and as far as I can tell it's a keeper :)
