### ISSUE TITLE
Font size not customisable?

### ISSUE THREAD

**Issue by nirurin** [lekeno/edr#303]
This one seems like a bug, as I have seen your videos and your font sizes are different to the defaults. 

I've already gone into the config file (as per the wiki) and changed a bunch of the overlay location (x/y coordinates) which works fine with a bit of trial and error. 

The 'general' font width and height parameters don't seem to change the size of the fonts though. They just change the height and width of the text 'containers'. So if I reduce the 'height', the lines of text will overlap with each other. Width seems to do nothing at all that I can tell.

**Comment by lekeno** [comment]
Hey, thanks for the report.

As you have noticed, the large_width and large_height (also normal_*)) variables in the config file are only meant to adjust the spacing of the text containers in case the default layout ends up with overlapping lines of text.

The width variable is only useful for text that's centered (none in the default layout, iirc).

The overlay I'm using was developed [by Ian Norton](https://github.com/inorton/EDMCOverlay) and doesn't support font sizes beside predefined large and normal values.
