### ISSUE TITLE
Module not found Error: Tkinter 

### ISSUE THREAD

**Issue by SweetyVolty** [lekeno/edr#318]
[EDMarketConnector.log](https://github.com/lekeno/edr/files/4775948/EDMarketConnector.log)

As seen on the log, no idea what is causing this nor what is tkinter :/

**Comment by lekeno** [comment]
Thanks for the report.

I'd recommend to use the latest 3.4 version of EDMarketConnector: https://github.com/Marginal/EDMarketConnector/releases/tag/rel-343

3.5 is a beta build designed for Python 3.7 and EDR doesn't work in that environment.

**Comment by SweetyVolty** [comment]
ah it worked when downgraded thanks :3
