### ISSUE TITLE
not compatible with Python 3.7 -- [EDCD/EDMarketConnector] Pre-release rel-351-0 - 3.51 beta0

### ISSUE THREAD

**Issue by feiercrack** [lekeno/edr#321]
current EDR is not working in the EDMC beta!

can this please be migrated to Python 3.7 for future versions of EDMC, because the current stable EDMC 3.46 is the LAST version released in Python 2.7

https://github.com/EDCD/EDMarketConnector/blob/master/PLUGINS.md#migration-to-python-37

https://github.com/EDCD/EDMarketConnector/releases/tag/rel-351-0

**Comment by lekeno** [comment]
Thanks for the heads-up.
I saw the change of ownership and decided to finally work on it.

The next version should be compatible with 3.7, you can test it out by overwriting the python files with those found in the 1.0.8 branch: https://github.com/lekeno/edr/tree/1.0.8

See issue #270, please reopen that one if it's still broken.

**Comment by feiercrack** [comment]
dunno if i did it right (copy-thing), but i had tested it, and it still doesnt work...
