### ISSUE TITLE
Illegible in when using ED:MC default theme

### ISSUE THREAD

**Issue by ewanm89** [lekeno/edr#325]
Looks like the text colour is hard coded rather than taken from the current ED:MC theme in the ED:MC window output, this makes it white on light grey making it illegible.

**Comment by lekeno** [comment]
Thanks for the report. There is indeed an issue where in the past the background would be correctly set to black, but it no longer is....

**Comment by lekeno** [comment]
I think I got it right this time. Thanks for the pointer in your fork, I've used something similar and added a refresh feature when the settings are changed.
