### ISSUE TITLE
No Anaconda crash at Renet B 1 (14 | 135)

### ISSUE THREAD

**Issue by FalcoGer** [lekeno/edr#421]
Maybe I'm doing something wrong. But there is no annaconda crash site at  Renet B 1 (14 | 135). I was looking around the area in a pretty wide circle and there was nothing there. I found a few cargo containers strewn about, but no crash site.
I didn't use probes, I just landed at the coordinates.

Running horizons, not odyssey.

![grafik](https://user-images.githubusercontent.com/16250196/140240737-8bf81af2-d536-4f34-9d57-3cd0ddfb8eeb.png)

**Comment by lekeno** [comment]
Thanks for the report.
I'm not sure why it's not there anymore. Maybe a glitch in one of the post-odyssey launch updates... 
I'll remove it in the next version of EDR.
