### ISSUE TITLE
Overlay not showing (Steam?)

### ISSUE THREAD

**Issue by idcowden** [lekeno/edr#433]
Hi,

I recently installed EDR. Even with the EDMCOverlay run manually whilst ELite (Oddyssey) is running, I can't get the EDR Overlay to appear. Have tried going from full screeen, to windowed to borderless, rebooting etc. 

I'm wondering if the Steam overlay software might be causing an issue with the EDR overlay?

**Comment by inorton** [comment]
It could be, have you tried turning it off?

**Comment by idcowden** [comment]
I haven't yet found a way to turn it off...

**Comment by idcowden** [comment]
Another update. If I launch EDMCOverlay manually I will occasionally see /EDMC OVERLAY/ overlaid on Elite Dangerous, but EDR stays stubbornly hidden. I can read updates on EDMC itself but I can't get the in game overlay to appear at all. I'm running EDDiscovery and EDMC...

**Comment by inorton** [comment]
@idcowden  are you using the latest version? that sounds a bit like a bug that used to happen if EDMC was started after Elite.

**Comment by idcowden** [comment]
I was on 1.9.3 - have just upgraded to 2.0.0, but no change,
Interestingly after upgrading windows tried to block EDMCOverlay - I prevented it. 
If run normally EDMCOVerlay keeps shutting down, if I run it as administrator it stays on, but no overlay is showing.
I had it running before starting ELite also.

**Comment by idcowden** [comment]
Just FYI - I win the stupid of the year award.
Somehow I managed to not spot that on the EDR config tab there is a little checkbox to turn the overlay on, which by default is *not* checked...

Having turned it on - it now works !
Thanks Lekeno :-)
