### ISSUE TITLE
System Language Loading Issue

### ISSUE THREAD

**Issue by GLWine** [lekeno/edr#487]
# Overview of the situation
When translating the EDR 2.6.1 plugin into my language (_Italian_) using the source file _edr.po_, I encountered an issue with the language loading. 
I made sure to place the _edr.mo_ file in its correct folder, maintaining the folder structure used in other configured languages. 
Unfortunately, the result was a lack of progress, as the plugin was loading in English, even though EDMC is correctly set to my system language (Windows 10 64-bit).

# Troubleshooting
At this point, I attempted to understand why this was happening but couldn't find a definitive solution. 
I suspect it's related to how EDMC saves the language value in the _config_ variable when the program is set to automatically detect the system language.

Upon further investigation, I realized that in the **edrclient.py** file, the function responsible for setting the plugin's language ( _set\_language()_ ), in turn, calls a function in EDMC ( _config.get\_str("language")_ ).
[edrclient.py](https://github.com/lekeno/edr/blob/2.6.1b/edr/edrclient.py)
```python
# Other code first
62    def __init__(self):
63        edr_config = EDRConfig()
#         "set_language" calls "config.get_str", which searches for text linked to "language".
64        set_language(config.get_str("language"))
65
66        self.edr_version = edr_config.edr_version()
67        EDRLOG.log(u"Version {}".format(self.edr_version), "INFO")
# Other code later
```

This function passes a request to look for the value associated with the "language" key in the _config_ variable, which is declared and managed in the **\_\_init\_\_.py** file.
[\_\_init\_\_.py](https://github.com/EDCD/EDMarketConnector/blob/develop/config/__init__.py)
```python
# Other code first
349    @abstractmethod
350    def get_str(self, key: str, *, default: str | None = None) -> str:
351        """
352        Return the string referred to by the given key if it exists, or the default.
353
354        :param key: The key data is being requested for.
355        :param default: Default to return if the key does not exist, defaults to None.
356        :raises ValueError: If an internal error occurs getting or converting a value.
357        :raises OSError: On Windows, if a Registry error occurs.
358        :return: The requested data or the default.
359        """
360        raise NotImplementedError
# Other code later
```

After this, the _set\_language()_ function takes over the response from EDMC's function. The _lang_ variable, initially initialized as _None_, is then overwritten with the information obtained from EDMC.
The function _set\_language()_ is described in the file **edr18ln.py** and is responsible for interpreting the argument assigned to it. 
The variable *lang*, initially initialized as *None*, is then overwritten with the information obtained from the EDMC function.
[edr18ln.py](https://github.com/lekeno/edr/blob/2.6.1b/edr/edri18n.py)
```python
# Other code first
14    language = None
15    translate = gettext.translation('edr', L10N_DIR, fallback=True)
16
17    def set_language(lang):
# Other code later
```

Next, an *if* statement checks whether the _lang_ variable differs from its initialization value, which is _None_. If the result is positive, it compares the content with the available languages and their positions. If it finds a match, it sets the plugin to use the requested language. If the result is negative, the _else_ statement loads the language set as default, which is English.
```python
# Other code first
17    def set_language(lang):
18        global language, translate
19        language = lang
#         Checks if "language" is unchanged from when "None" was defined
20        if language:
#             Set "translate" according to the parameters indicated below
21            translate = gettext.translation('edr', L10N_DIR, fallback=True, languages=[language])
#         When "language" is set as "None" do this:
22        else:
#             By not passing on a language to him, he will keep English 
23            translate = gettext.translation('edr', L10N_DIR, fallback=True)
# Other code later
```

All of this works well only if EDMC explicitly specifies a language to load in the File->Settings->Appearance panel. However, if the language is set to "Default," it means that the "language" key is not associated with anything, and thus, when searched for, it returns the value _None_.

# Final Comments
The issue now lies in correctly loading the EDR language even when not explicitly specified in EDMC and instead determined by the system.
 
# Acknowledgments
Thank you for supporting Discord users:
- a_dragon1337 _Aka_ (A_D (EDMC))
- berndulas _Aka_ (Gazelle (TD))
- athanspod _Aka_ (Athanasius (Retired))
- @lekeno 

## Post credits
I also presented the problem on Discord as the user: [JumpFrost_ITA](https://discordapp.com/users/457968370390663199). To be fair, I opened a ticket here too, so I can keep track of it and describe it clearly and comprehensively.
However, I await developments in this regard from the developers, provided they deem it necessary to dedicate time to solving the problem.

**Comment by lekeno** [comment]
Sorry for the delay. I looked a bit and I don't see a robust way of finding the OS' default language. The getdefaultlocale() method seems like it would be perfect but it's deprecated.

In the meantime, does it work if you manually set EDMC to your preferred language, even if it's the same as your OS' language? 

Note: The **.mo** file should be under `\l10n\it\LC_MESSAGES`.

**Comment by GLWine** [comment]
A solution to the problem is proposed in the Pull Request lekeno/edr#512
