### ISSUE TITLE
[Bug] Possible errors detected in the code

### ISSUE THREAD

**Issue by GLWine** [lekeno/edr#526]
# I report some errors in the code that I found:
While looking through the various files that make EDR work I noticed some oddities in the code. I think they deserve a closer look.
## Code to check in `ingamemsg.py` file
>### Separation between static string and dynamic components
><details>
><summary>More details</summary>
>
> Strings are specified by not enclosing the static part in brackets, this means that when the string is called, gettext will find itself with the already integrated string of the dynamic part and therefore will not find it in the language files.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/ingamemsg.py#L488
>
></details>

## Code to check in `edrsystem.py` file
>### Duplicate `station` function
><details>
><summary>More details</summary>
>The first definition of the function is on line 286, the subsequent redefinitions are on lines 707 and 780.
>The three versions seem to be completely identical, there are no apparent differences in the code, or indentation. 
>This could lead to problems if one of these were changed, at which point the code would not work as expected.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrsystems.py#L286-L304 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrsystems.py#L707-L725 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrsystems.py#L780-L798
>
></details>

>### Duplicate `kv_lut` dictionary key
><details>
><summary>More details</summary>
>
>There is the same key for two elements with different characteristics, making it difficult to find one element harder than the other.
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrsystems.py#L1597 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrsystems.py#L1617
>
></details>

>### Duplicate `value` dictionary key
><details>
><summary>More details</summary>
>
>There is the same key for two elements with different characteristics, making it difficult to find one element harder than the other.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrsystems.py#L1938-L1943
>
></details>

## Code to check in `edrroutes.py` file
>### Separation between static string and dynamic components
><details>
><summary>More details</summary>
>
> Strings are specified by not enclosing the static part in brackets, this means that when the string is called, gettext will find itself with the already integrated string of the dynamic part and therefore will not find it in the language files.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrroutes.py#L576
>
></details>

## Code to check in `edrinventory.py` file
>### Duplicate `traded` function
><details>
><summary>More details</summary>
>The first definition of the function is on line 663, the next re-definition is on line 806. The two versions have some differences.
>I am not sure which function will actually be called between the two, if you want to speculate it is possible that the one further down in >Athe code will be called.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L663-L670 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L806-L816
>
></details>

>### Strings candidates to become translatable
><details>
><summary>More details</summary>
>
>I think these strings could be added to the translatable ones.
>If accepted for translation, the static part should be enclosed in a `_().format`.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L727 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L738 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L740
>
></details>

>### Separation between static string and dynamic components
><details>
><summary>More details</summary>
>
> Strings are specified by not enclosing the static part in brackets, this means that when the string is called, gettext will find itself with the already integrated string of the dynamic part and therefore will not find it in the language files.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1165 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1167 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1181 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1184 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1187 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1226 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1237 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1264
>
></details>

## Code to check in `edrfssinsights.py` file
>### Duplicate `signals` dictionary key
><details>
><summary>More details</summary>
>
>There is the same key for two elements with different characteristics, making it difficult to find one element harder than the other.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrfssinsights.py#L20-L21
>
></details>

## Code to check in `edrclient.py` file
>### Strings candidates to become translatable
><details>
><summary>More details</summary>
>
>I think these strings could be added to the translatable ones.
>If accepted for translation, the static part should be enclosed in a `_().format`.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L2626-L2628 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L3690
>
></details>

>### Separation between static string and dynamic components
><details>
><summary>More details</summary>
>
> Strings are specified by not enclosing the static part in brackets, this means that when the string is called, gettext will find itself with the already integrated string of the dynamic part and therefore will not find it in the language files.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L644 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L1519 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L1532 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L3839 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L3934 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L3963 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L3981 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrclient.py#L3996
>
></details>

**Comment by lekeno** [comment]
Started to fix the low hanging fruits.
I'll look more carefully at the rest since there might be some unintended effects.

**Comment by GLWine** [comment]
# Found more possible errors:
## Code to check in `edrinventory.py` file
>### Regex pattern with raw literal strings
><details>
><summary>More details</summary>
>
>Strings passed to the `re.sub()` method should be passed as raw strings using `r"text"`
>Source: https://docs.python.org/3/library/re.html
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1122 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L1322
>
>At that point the code would be rewritten like this:
>```python
>c_item = re.sub(r"[ -_]", "", c_item)
>```
>
></details>

## Code to check in `edri18n.py` file
>### I made a mistake calling the `.error()` method of the `EDRLog()` instance
><details>
><summary>More details</summary>
>
>In `line 46` I mistakenly called a non-existent method `.error()`, it should be changed to `.log()`.
>In all three lines the error level should be changed from `DEBUG` to `ERROR` for consistency with the exception.
>
>| Errore | Fix |
>| --- | --- |
>|https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edri18n.py#L46 | `EDRLOG.log("AttributeError occurred: {}.".format(e), "ERROR")` |
>| https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edri18n.py#L50|`EDRLOG.log(u"Error occurred: {}.".format(e), "ERROR")` |
>| https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edri18n.py#L54 |`EDRLOG.log(u"An unexpected error occurred: {}.".format(e), "ERROR")` |
>
></details>

## Code to check in `edInstance.py` file
>### Strings candidates to become translatable
><details>
><summary>More details</summary>
>
>I think these strings could be added to the translatable ones.
>If accepted for translation, the static part should be enclosed in a `_().format`.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edinstance.py#L150 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edinstance.py#L156 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edinstance.py#L163
>
></details>
## Code to check in `igmconfig.py` file
>### Not all arguments converted during string formatting
><details>
><summary>More details</summary>
>
> The problem occurs in the line below, because the string `"#{}"` contains only one placeholder, but two arguments are provided to `format()`.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/igmconfig.py#L77
>
></details>

>### Direct call to the `EDRLog()` instance
><details>
><summary>More details</summary>
>
> In the following lines the `EDRLog()` instance is called directly instead of defining a global constant variable that contains the logger instance
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/igmconfig.py#L22 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/igmconfig.py#L25 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/igmconfig.py#L28 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/igmconfig.py#L31
>
></details>

## Code to check in `audiofeedback.py` file
>### Direct call to the `EDRLog()` instance
><details>
><summary>More details</summary>
>
>The `EDRLog()` instance is used directly, however to conform to the rest of the code you could insert a global constant variable at the beginning that takes care of doing this.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/audiofeedback.py#L91 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/audiofeedback.py#L94
>```python
>EDRLOG = edrlog.EDRLog()
>```
>
></details>

## Code to check in `edrcommands.py` file
>### Direct call to the `EDRLog()` instance
><details>
><summary>More details</summary>
>
>In `line 14` a local variable is created that contains the instance of `EDRLog()`, you could create a global constant variable that contains the instance, and fix the call in the code.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrcommands.py#L8-L14
>```python
>EDRLOG = edrlog.EDRLog()
>```
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrcommands.py#L39 there are about 50 lines to change
>```python
>EDRLOG.log(u"Implicit who command for {}".format(recipient), "INFO")
>```
>
></details>

## Code to check in `edrrealtime.py` file
>### Assigning the `EDRLog()` method to a local constant variable
><details>
><summary>More details</summary>
>
> The `EDRLog()` method is assigned to the same local constant variable `edr_log` in two different methods, at this point I think we can opt for creating a single global constant variable.
>
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrrealtime.py#L100-L118 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrrealtime.py#L140-L147
>
></details>

## Note:
> You could insert directly into the `edrlog.py` file a global constant variable `EDRLOG = EDRLog()` or even better `EDRLOG = EDRLog.log()`
>So you can have it always everywhere without having to declare it every time
> This would involve aligning all code to this statement: `from edrlog import EDRLOG`, which should suffice as a workaround almost everywhere.

**Comment by lekeno** [comment]
I think I took care of the second batch with the exception of "Strings candidates to become translatable". Those are for debugging purpose, so no need to translate them.

Thanks again for these in depth reports.

**Comment by GLWine** [comment]
## Found an additional error:
## Code to check in `edrinventory.py` file
>### Calling a global variable as if it were a class variable
><details>
><summary>More details</summary>
>
>The constant variable `MATERIALS_LUT` is defined outside the `EDRInventory()` class, however the static method `readable()` tries to access the variable as if it were in the class.
>https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L18-L21 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L383-L393 https://github.com/lekeno/edr/blob/757e6992f72265e2d14c3d6c99eaaa8aab276712/edr/edrinventory.py#L965-L970
>
>At that point the code would be rewritten like this:
>```python
>@staticmethod
>def readable(name):
>    cname = name.lower()
>    if cname in MATERIALS_LUT:
>        return MATERIALS_LUT[cname].get("localized", name)
>    return name
>```
>
></details>

**Comment by GLWine** [comment]
# Checklist of checked issues: 
- [x] **Code to check in `ingamemsg.py` file**
  - [x] Separation between static string and dynamic components
    - (commit 4936bb4)

- [ ] **Code to check in `edrsystem.py` file**
  - [x] Duplicate `station()` function
    - (commit 4936bb4)
  - [ ] Duplicate `kv_lut{}` dictionary key
  - [ ] Duplicate `value{}` dictionary key

- [x] **Code to check in `edrroutes.py` file**
  - [x] Separation between static string and dynamic components
    - (commit 4936bb4)

- [ ] **Code to check in `edrinventory.py` file**
  - [ ] Duplicate `traded()` function
  - [x] Strings candidates to become translatable
    - (rejected)
  - [x] Separation between static string and dynamic components
    - (commit 97729e5)
  - [x] Regex pattern with raw literal strings
    - (commit c6aded4)
  - [ ] Calling a global variable as if it were a class variable

- [x] **Code to check in `edrfssinsights.py` file**
  - [x] Duplicate `signals{}` dictionary key
    - (commit 4936bb4)

- [x] **Code to check in `edrclient.py` file**
  - [x] Strings candidates to become translatable
    - (rejected)
  - [x] Separation between static string and dynamic components
    - (commit 4936bb4)

- [x] **Code to check in `edri18n.py` file**
  - [x] I made a mistake calling the `.error()` method of the `EDRLog()` instance
    - (commit 0c4ad33)

- [x] **Code to check in `edinstance.py` file**
  - [x] Strings candidates to become translatable
    - (rejected)

- [ ] **Code to check in `igmconfig.py` file**
  - [ ] Not all arguments converted during string formatting
  - [x] Direct call to the `EDRLog()` instance
    - (commit 0c4ad33)

- [x] **Code to check in `audiofeedback.py` file**
  - [x] Direct call to the `EDRLog()` instance 
    - (commit 0c4ad33)

- [x] **Code to check in `edrcommands.py` file**
  - [x] Direct call to the `EDRLog()` instance
    - (commit 0c4ad33)

- [x] **Code to check in `edrrealtime.py` file**
  - [x] Assigning the `EDRLog()` method to a local constant variable
    - (commit 0c4ad33)

- [x] **Added global constant class to `edrlog.py`**
  - [x] Assigning the `EDRLog()` method to a global constant variable `EDR_LOG`
    - (commit 0c4ad33)

**Comment by lekeno** [comment]
I believe that everything has been taken care of.
Needs to be tested though :)

**Comment by GLWine** [comment]
@lekeno 
> I believe that everything has been taken care of. Needs to be tested though :)

I'll download this version and test it, let's say, even if I can't see everything properly
